// This file is intentionally without code.
// It's present so that service worker registration will work when serving from the 'app' directory.
// The version of service-worker.js that's present in the 'dist' directory is automatically
// generated by the 'generate-service-worker' gulp task, and contains code to precache resources.
console.log("SW startup");

self.addEventListener('install', function(event) 
{
	console.log("SW installed");
});

self.addEventListener('activate', function(event) 
{
	console.log("SW activated");
});

self.addEventListener('fetch', function(event) 
{
	console.log("Caught a fetch!");
	console.log(event.request);
	
	/*event.respondWith(new Response("Hello world!"));*/
});
